export const actionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  CART: "CART",
  SELECTED_ITEMS: "SELECTED_ITEMS",
  RATED_ITEMS: "RATED_ITEMS",
  IS_RATED: "IS_RATED",
};
